### PR TITLE
Removed case sensitive for url input

### PR DESCRIPTION
**Pull request by Night1**
There is no need for this to be case sensitive as neither DNS nor sslscan.sh behaves different on case input for url.

### CODE REVIEW

**Comment by thomaspatzke** [comment]
Thanks for the PR! Yes, that's true. This is the reason why this RE accepts all cases. Users often copy&paste the values from lists with upper cased host names. Changing this check would causing the rejection of such requests that normally would executed fine.

**Comment by Night1** [comment]
Yeah, that is why I did the PR, annoyed me one time and fix was simple regex update.
I did some testing with several domains with upper and lower case no adverse effects was present, all that should have passed did pass.   Just a few bugs with TLSv1.3 but those were expected. 


Should it not also allow international symbols as per RFC 3454, RFC 3490, RFC 3491 and RFC 3492, (IDN)?
Since now domains also includes localized characters like "åøæüëïß" and then some.

**Comment by thomaspatzke** [comment]
Ah, sorry! Mismatched something, now it's merged!

The intended usage of this was to offer TLS config scans in internal corporate networks, were IDN domains are quite uncommon. Until now, nobody complained, but feel free to add them.

**Comment by Night1** [comment]
No issue,  I do se the use for this to be used on internal networks, but no issue that it also supports external scans, as some of my services both work internal and external with differnet cipher suits. 

I have seen some internal networks with uses IDNs for their domains but not many.

**Pull request merged**
